//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PavelStransky.Expression {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PavelStransky.Expression.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase the variable from the global context.
        /// </summary>
        internal static string ClearGlobalHelp {
            get {
                return ResourceManager.GetString("ClearGlobalHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; has bad type..
        /// </summary>
        internal static string EMBadParamType {
            get {
                return ResourceManager.GetString("EMBadParamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct type: {0}\r\nEntered type: {1}.
        /// </summary>
        internal static string EMBadParamTypeDetail {
            get {
                return ResourceManager.GetString("EMBadParamTypeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &quot;{0}&quot; of a variable has not valid format..
        /// </summary>
        internal static string EMBadVariableName {
            get {
                return ResourceManager.GetString("EMBadVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must not contain the character &quot;{0}&quot; at position {1}..
        /// </summary>
        internal static string EMBadVariableNameInvalidCharacter {
            get {
                return ResourceManager.GetString("EMBadVariableNameInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be no spaces in it..
        /// </summary>
        internal static string EMBadVariableNameNoSpace {
            get {
                return ResourceManager.GetString("EMBadVariableNameNoSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you &quot;{0}&quot; have specified does not exist..
        /// </summary>
        internal static string EMFileNotExist {
            get {
                return ResourceManager.GetString("EMFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify the name of the file..
        /// </summary>
        internal static string EMNoFile {
            get {
                return ResourceManager.GetString("EMNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the considered operation the rank of the Array must be equals to 1..
        /// </summary>
        internal static string EMNot1D {
            get {
                return ResourceManager.GetString("EMNot1D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lengths of the given objects must be equal..
        /// </summary>
        internal static string EMNotEqualLength {
            get {
                return ResourceManager.GetString("EMNotEqualLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of the first object: {0}\r\nLength of the second object: {1}.
        /// </summary>
        internal static string EMNotEqualLengthDetail {
            get {
                return ResourceManager.GetString("EMNotEqualLengthDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The elements of the given list have not equal types..
        /// </summary>
        internal static string EMNotEqualTypes {
            get {
                return ResourceManager.GetString("EMNotEqualTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; (position {1}) of the function &quot;{2}&quot; is obligatory and cannot be omited..
        /// </summary>
        internal static string EMObligatoryParameter {
            get {
                return ResourceManager.GetString("EMObligatoryParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using the operator &apos;{0}&apos; between array requires the length  ({1}, {2}) to be equals..
        /// </summary>
        internal static string EMOperatorArrayLength {
            get {
                return ResourceManager.GetString("EMOperatorArrayLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to use the operator &apos;{0}&apos; between these types: {1} {0} {2}..
        /// </summary>
        internal static string EMOperatorUnknownType {
            get {
                return ResourceManager.GetString("EMOperatorUnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank of the Array = {0}..
        /// </summary>
        internal static string EMRankDetail {
            get {
                return ResourceManager.GetString("EMRankDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &quot;{0}&quot; cannot be set..
        /// </summary>
        internal static string EMVarCannotBeSet {
            get {
                return ResourceManager.GetString("EMVarCannotBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the list must not be zero..
        /// </summary>
        internal static string EMZeroLengthList {
            get {
                return ResourceManager.GetString("EMZeroLengthList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute value.
        /// </summary>
        internal static string HelpAbs {
            get {
                return ResourceManager.GetString("HelpAbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds an element to the end of the list.
        /// </summary>
        internal static string HelpAdd {
            get {
                return ResourceManager.GetString("HelpAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds an element to the end of the list in the global context.
        /// </summary>
        internal static string HelpAddGlobal {
            get {
                return ResourceManager.GetString("HelpAddGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arcus tangens of the value.
        /// </summary>
        internal static string HelpArcTan {
            get {
                return ResourceManager.GetString("HelpArcTan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For given dynamical system and energy determines the bounds (higher limit) in which the solution can be found.
        /// </summary>
        internal static string HelpBounds {
            get {
                return ResourceManager.GetString("HelpBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a ClassicalGCM class (nonrotating case with simple kinetic term).
        /// </summary>
        internal static string HelpCGCM {
            get {
                return ResourceManager.GetString("HelpCGCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a ClassicalGCMJ class (case with nonzero angular momentum).
        /// </summary>
        internal static string HelpCGCMJ {
            get {
                return ResourceManager.GetString("HelpCGCMJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a ClassicalIBM class.
        /// </summary>
        internal static string HelpCIBM {
            get {
                return ResourceManager.GetString("HelpCIBM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase the variable (all variables if nothing is specified) from the context.
        /// </summary>
        internal static string HelpClear {
            get {
                return ResourceManager.GetString("HelpClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new context.
        /// </summary>
        internal static string HelpContext {
            get {
                return ResourceManager.GetString("HelpContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given array transforms into one dimensional array.
        /// </summary>
        internal static string HelpDeflate {
            get {
                return ResourceManager.GetString("HelpDeflate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For given dynamical system and position in the phase space calculates the energy.
        /// </summary>
        internal static string HelpEnergy {
            get {
                return ResourceManager.GetString("HelpEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For GCM system and given energy calculates equipotential contour.
        /// </summary>
        internal static string HelpEquipotential {
            get {
                return ResourceManager.GetString("HelpEquipotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates an ExtendedClassicalGCM class with mass proportional to beta^2.
        /// </summary>
        internal static string HelpExtendedCGCM1 {
            get {
                return ResourceManager.GetString("HelpExtendedCGCM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates an ExtendedClassicalGCM class with kinetic term proportional to beta^2.
        /// </summary>
        internal static string HelpExtendedCGCM2 {
            get {
                return ResourceManager.GetString("HelpExtendedCGCM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factorial of the value.
        /// </summary>
        internal static string HelpFactorial {
            get {
                return ResourceManager.GetString("HelpFactorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives the spectrum of a vector using Fast Fourier Transform (FFT).
        /// </summary>
        internal static string HelpFFTSpectrum {
            get {
                return ResourceManager.GetString("HelpFFTSpectrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full help for the given function (including names and types of the parameters).
        /// </summary>
        internal static string HelpFullHelp {
            get {
                return ResourceManager.GetString("HelpFullHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns actual context.
        /// </summary>
        internal static string HelpGetContext {
            get {
                return ResourceManager.GetString("HelpGetContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns global context.
        /// </summary>
        internal static string HelpGetGlobalContext {
            get {
                return ResourceManager.GetString("HelpGetGlobalContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets out a variable from the global context.
        /// </summary>
        internal static string HelpGetGlobalVar {
            get {
                return ResourceManager.GetString("HelpGetGlobalVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns a variable from a given context.
        /// </summary>
        internal static string HelpGetVar {
            get {
                return ResourceManager.GetString("HelpGetVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create graph.
        /// </summary>
        internal static string HelpGraph {
            get {
                return ResourceManager.GetString("HelpGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a HenonHeiles class.
        /// </summary>
        internal static string HelpHH {
            get {
                return ResourceManager.GetString("HelpHH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For given dynamical system and energy generates initial condition of a trajectory and returns it as Vector.
        /// </summary>
        internal static string HelpInitialCondition {
            get {
                return ResourceManager.GetString("HelpInitialCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates points for interval (as an array).
        /// </summary>
        internal static string HelpIntervalA {
            get {
                return ResourceManager.GetString("HelpIntervalA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates points for interval (in the form PointVector(0, interval points)).
        /// </summary>
        internal static string HelpIntervalPV {
            get {
                return ResourceManager.GetString("HelpIntervalPV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates points for interval.
        /// </summary>
        internal static string HelpIntervalV {
            get {
                return ResourceManager.GetString("HelpIntervalV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigensystem of a matrix calculated using Jacobi method; before calculation it makes symmetrization of a matrix.
        /// </summary>
        internal static string HelpJacobi {
            get {
                return ResourceManager.GetString("HelpJacobi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array of vectors or array of pointVectors joins into one Vector.
        /// </summary>
        internal static string HelpJoin {
            get {
                return ResourceManager.GetString("HelpJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of the Laguerre polynomial.
        /// </summary>
        internal static string HelpLaguerre {
            get {
                return ResourceManager.GetString("HelpLaguerre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of the Legendre polynomial.
        /// </summary>
        internal static string HelpLegendre {
            get {
                return ResourceManager.GetString("HelpLegendre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns length(s) or number of elements of a given object as an array.
        /// </summary>
        internal static string HelpLength {
            get {
                return ResourceManager.GetString("HelpLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logarithm of the value (with specified base).
        /// </summary>
        internal static string HelpLog {
            get {
                return ResourceManager.GetString("HelpLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given vectors put onto columns of a matrix.
        /// </summary>
        internal static string MatrixColumnHelp {
            get {
                return ResourceManager.GetString("MatrixColumnHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given vectors put onto rows of a matrix.
        /// </summary>
        internal static string MatrixRowHelp {
            get {
                return ResourceManager.GetString("MatrixRowHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `.
        /// </summary>
        internal static string MsgParsing {
            get {
                return ResourceManager.GetString("MsgParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading page....
        /// </summary>
        internal static string MsgReadingPage {
            get {
                return ResourceManager.GetString("MsgReadingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norm of the vector.
        /// </summary>
        internal static string NormHelp {
            get {
                return ResourceManager.GetString("NormHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v.
        /// </summary>
        internal static string NormP1 {
            get {
                return ResourceManager.GetString("NormP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vector which norm is calculated.
        /// </summary>
        internal static string NormP1Description {
            get {
                return ResourceManager.GetString("NormP1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normpow.
        /// </summary>
        internal static string NormP2 {
            get {
                return ResourceManager.GetString("NormP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power of items.
        /// </summary>
        internal static string NormP2Description {
            get {
                return ResourceManager.GetString("NormP2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reads all known isotopes from http://www-nds.iaea.org.
        /// </summary>
        internal static string NuDatReadKnownIsotopesHelp {
            get {
                return ResourceManager.GetString("NuDatReadKnownIsotopesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reads all accessible pieces of information about a nucleus from http://www-nds.iaea.org.
        /// </summary>
        internal static string NuDatReadNucleusHelp {
            get {
                return ResourceManager.GetString("NuDatReadNucleusHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading page of nucleus {0}....
        /// </summary>
        internal static string NuDatReadNucleusPage {
            get {
                return ResourceManager.GetString("NuDatReadNucleusPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands that will be run on the new context.
        /// </summary>
        internal static string P1ContextDescription {
            get {
                return ResourceManager.GetString("P1ContextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string P1Deflate {
            get {
                return ResourceManager.GetString("P1Deflate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array to be deflated.
        /// </summary>
        internal static string P1DeflateDescription {
            get {
                return ResourceManager.GetString("P1DeflateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data.
        /// </summary>
        internal static string P1Graph {
            get {
                return ResourceManager.GetString("P1Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data for curves.
        /// </summary>
        internal static string P1GraphDescription {
            get {
                return ResourceManager.GetString("P1GraphDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v.
        /// </summary>
        internal static string P1Join {
            get {
                return ResourceManager.GetString("P1Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data to be joined.
        /// </summary>
        internal static string P1JoinDescription {
            get {
                return ResourceManager.GetString("P1JoinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of a variable that will be copied from actual context.
        /// </summary>
        internal static string P2ContextDescription {
            get {
                return ResourceManager.GetString("P2ContextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to background.
        /// </summary>
        internal static string P2Graph {
            get {
                return ResourceManager.GetString("P2Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data for background (mesh graph).
        /// </summary>
        internal static string P2GraphDescription {
            get {
                return ResourceManager.GetString("P2GraphDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to points.
        /// </summary>
        internal static string P3Equipotential {
            get {
                return ResourceManager.GetString("P3Equipotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of points of the equipotential contour.
        /// </summary>
        internal static string P3EquipotentialDescription {
            get {
                return ResourceManager.GetString("P3EquipotentialDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        internal static string P3Graph {
            get {
                return ResourceManager.GetString("P3Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error bars for data.
        /// </summary>
        internal static string P3GraphDescription {
            get {
                return ResourceManager.GetString("P3GraphDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to param.
        /// </summary>
        internal static string P3InitialCondition {
            get {
                return ResourceManager.GetString("P3InitialCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional parameter (angular momentum).
        /// </summary>
        internal static string P3InitialConditionDescription {
            get {
                return ResourceManager.GetString("P3InitialConditionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pglobal.
        /// </summary>
        internal static string P4Graph {
            get {
                return ResourceManager.GetString("P4Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters for the whole graph.
        /// </summary>
        internal static string P4GraphDescription {
            get {
                return ResourceManager.GetString("P4GraphDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pgroups.
        /// </summary>
        internal static string P5Graph {
            get {
                return ResourceManager.GetString("P5Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters for groups of data.
        /// </summary>
        internal static string P5GraphDescription {
            get {
                return ResourceManager.GetString("P5GraphDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pcurves.
        /// </summary>
        internal static string P6Graph {
            get {
                return ResourceManager.GetString("P6Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters for curves.
        /// </summary>
        internal static string P6GraphDescription {
            get {
                return ResourceManager.GetString("P6GraphDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string PA {
            get {
                return ResourceManager.GetString("PA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A parameter of GCM.
        /// </summary>
        internal static string PADescription {
            get {
                return ResourceManager.GetString("PADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string PAssociatedOrder {
            get {
                return ResourceManager.GetString("PAssociatedOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associated order of the polynomial.
        /// </summary>
        internal static string PAssociatedOrderDetail {
            get {
                return ResourceManager.GetString("PAssociatedOrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b.
        /// </summary>
        internal static string PB {
            get {
                return ResourceManager.GetString("PB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to base.
        /// </summary>
        internal static string PBase {
            get {
                return ResourceManager.GetString("PBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base of the logarithm.
        /// </summary>
        internal static string PBaseDescription {
            get {
                return ResourceManager.GetString("PBaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B parameter of GCM.
        /// </summary>
        internal static string PBDescription {
            get {
                return ResourceManager.GetString("PBDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c.
        /// </summary>
        internal static string PC {
            get {
                return ResourceManager.GetString("PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C parameter of GCM.
        /// </summary>
        internal static string PCDescription {
            get {
                return ResourceManager.GetString("PCDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commands.
        /// </summary>
        internal static string PCommands {
            get {
                return ResourceManager.GetString("PCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands to be calculated.
        /// </summary>
        internal static string PCommandsDescription {
            get {
                return ResourceManager.GetString("PCommandsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to context.
        /// </summary>
        internal static string PContext {
            get {
                return ResourceManager.GetString("PContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given context.
        /// </summary>
        internal static string PContextDescription {
            get {
                return ResourceManager.GetString("PContextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        internal static string PDefaultValue {
            get {
                return ResourceManager.GetString("PDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value of the variable.
        /// </summary>
        internal static string PDefaultValueDescription {
            get {
                return ResourceManager.GetString("PDefaultValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        internal static string PDiagonalValue {
            get {
                return ResourceManager.GetString("PDiagonalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value(s) to be put onto diagonal.
        /// </summary>
        internal static string PDiagonalValueDescription {
            get {
                return ResourceManager.GetString("PDiagonalValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dynamicalsystem.
        /// </summary>
        internal static string PDynamicalSystem {
            get {
                return ResourceManager.GetString("PDynamicalSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamical system.
        /// </summary>
        internal static string PDynamicalSystemDescription {
            get {
                return ResourceManager.GetString("PDynamicalSystemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to endx.
        /// </summary>
        internal static string PEndingPoint {
            get {
                return ResourceManager.GetString("PEndingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending point of the interval.
        /// </summary>
        internal static string PEndingPointDetail {
            get {
                return ResourceManager.GetString("PEndingPointDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to energy.
        /// </summary>
        internal static string PEnergy {
            get {
                return ResourceManager.GetString("PEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy of the system.
        /// </summary>
        internal static string PEnergyDescription {
            get {
                return ResourceManager.GetString("PEnergyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p.
        /// </summary>
        internal static string PExtendedGCM {
            get {
                return ResourceManager.GetString("PExtendedGCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter extending mass coeficient.
        /// </summary>
        internal static string PExtendedGCMDescription {
            get {
                return ResourceManager.GetString("PExtendedGCMDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fnname.
        /// </summary>
        internal static string PFnName {
            get {
                return ResourceManager.GetString("PFnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of a function.
        /// </summary>
        internal static string PFnNameDescription {
            get {
                return ResourceManager.GetString("PFnNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gamma.
        /// </summary>
        internal static string PGamma {
            get {
                return ResourceManager.GetString("PGamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamma coordinate of the GCM.
        /// </summary>
        internal static string PGammaDetail {
            get {
                return ResourceManager.GetString("PGammaDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gcm.
        /// </summary>
        internal static string PGCM {
            get {
                return ResourceManager.GetString("PGCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCM class.
        /// </summary>
        internal static string PGCMDescription {
            get {
                return ResourceManager.GetString("PGCMDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to graph.
        /// </summary>
        internal static string PGraph {
            get {
                return ResourceManager.GetString("PGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph object (created usually by graph command).
        /// </summary>
        internal static string PGraphDescription {
            get {
                return ResourceManager.GetString("PGraphDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to graphname.
        /// </summary>
        internal static string PGraphName {
            get {
                return ResourceManager.GetString("PGraphName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the graph (will be shown in the graph caption).
        /// </summary>
        internal static string PGraphNameDescription {
            get {
                return ResourceManager.GetString("PGraphNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chi.
        /// </summary>
        internal static string PIBMChi {
            get {
                return ResourceManager.GetString("PIBMChi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi parameter of IBM.
        /// </summary>
        internal static string PIBMChiDescription {
            get {
                return ResourceManager.GetString("PIBMChiDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eta.
        /// </summary>
        internal static string PIBMEta {
            get {
                return ResourceManager.GetString("PIBMEta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eta parameter of IBM.
        /// </summary>
        internal static string PIBMEtaDescription {
            get {
                return ResourceManager.GetString("PIBMEtaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of Pi number.
        /// </summary>
        internal static string PiHelp {
            get {
                return ResourceManager.GetString("PiHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item.
        /// </summary>
        internal static string PItem {
            get {
                return ResourceManager.GetString("PItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item to be added to the end of the list.
        /// </summary>
        internal static string PItemDescription {
            get {
                return ResourceManager.GetString("PItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to k.
        /// </summary>
        internal static string PK {
            get {
                return ResourceManager.GetString("PK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K (mass) parameter of GCM.
        /// </summary>
        internal static string PKDescription {
            get {
                return ResourceManager.GetString("PKDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to column.
        /// </summary>
        internal static string PMatrixColumn {
            get {
                return ResourceManager.GetString("PMatrixColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data for a column.
        /// </summary>
        internal static string PMatrixColumnDescription {
            get {
                return ResourceManager.GetString("PMatrixColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to row.
        /// </summary>
        internal static string PMatrixRow {
            get {
                return ResourceManager.GetString("PMatrixRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data for a row.
        /// </summary>
        internal static string PMatrixRowDescription {
            get {
                return ResourceManager.GetString("PMatrixRowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nd.
        /// </summary>
        internal static string PNonDiagonalValue {
            get {
                return ResourceManager.GetString("PNonDiagonalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value to be put instead of all nondiagonal elements.
        /// </summary>
        internal static string PNonDiagonalValueDescription {
            get {
                return ResourceManager.GetString("PNonDiagonalValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nucleus.
        /// </summary>
        internal static string PNucleus {
            get {
                return ResourceManager.GetString("PNucleus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labeling of a nucleus.
        /// </summary>
        internal static string PNucleusDescription {
            get {
                return ResourceManager.GetString("PNucleusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numx.
        /// </summary>
        internal static string PNumberOfPoints {
            get {
                return ResourceManager.GetString("PNumberOfPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of points in the interval.
        /// </summary>
        internal static string PNumberOfPointsDetail {
            get {
                return ResourceManager.GetString("PNumberOfPointsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ncolumns.
        /// </summary>
        internal static string PNumColumns {
            get {
                return ResourceManager.GetString("PNumColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of columns in an array of graphs.
        /// </summary>
        internal static string PNumColumnsDescription {
            get {
                return ResourceManager.GetString("PNumColumnsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculates a Poincaré section for given energy or trajectory given by its initial condition.
        /// </summary>
        internal static string PoincareHelp {
            get {
                return ResourceManager.GetString("PoincareHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ic.
        /// </summary>
        internal static string PoincareP2 {
            get {
                return ResourceManager.GetString("PoincareP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial condition of a trajectory or energy if the trajectory is randomly chosen.
        /// </summary>
        internal static string PoincareP2Description {
            get {
                return ResourceManager.GetString("PoincareP2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to points.
        /// </summary>
        internal static string PoincareP3 {
            get {
                return ResourceManager.GetString("PoincareP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of points of the final section.
        /// </summary>
        internal static string PoincareP3Description {
            get {
                return ResourceManager.GetString("PoincareP3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sectionplane.
        /// </summary>
        internal static string PoincareP4 {
            get {
                return ResourceManager.GetString("PoincareP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plane of the section.
        /// </summary>
        internal static string PoincareP4Description {
            get {
                return ResourceManager.GetString("PoincareP4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c1.
        /// </summary>
        internal static string PoincareP5 {
            get {
                return ResourceManager.GetString("PoincareP5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First coordinate of the phase space which will be stored.
        /// </summary>
        internal static string PoincareP5Description {
            get {
                return ResourceManager.GetString("PoincareP5Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c2.
        /// </summary>
        internal static string PoincareP6 {
            get {
                return ResourceManager.GetString("PoincareP6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second coordinate of the phase space which will be stored.
        /// </summary>
        internal static string PoincareP6Description {
            get {
                return ResourceManager.GetString("PoincareP6Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of Poisson distribution.
        /// </summary>
        internal static string PoissonHelp {
            get {
                return ResourceManager.GetString("PoissonHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data of input vector interprets as coeficients of polynom and return its value.
        /// </summary>
        internal static string PolynomHelp {
            get {
                return ResourceManager.GetString("PolynomHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n.
        /// </summary>
        internal static string POrder {
            get {
                return ResourceManager.GetString("POrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order of the polynomial.
        /// </summary>
        internal static string POrderDetail {
            get {
                return ResourceManager.GetString("POrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For GCM system solves the equation Potential == Given energy.
        /// </summary>
        internal static string PotentialRootsHelp {
            get {
                return ResourceManager.GetString("PotentialRootsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to psposition.
        /// </summary>
        internal static string PPhaseSpacePosition {
            get {
                return ResourceManager.GetString("PPhaseSpacePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position in the phase space.
        /// </summary>
        internal static string PPhaseSpacePositionDescription {
            get {
                return ResourceManager.GetString("PPhaseSpacePositionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pcoef.
        /// </summary>
        internal static string PPolynomCoef {
            get {
                return ResourceManager.GetString("PPolynomCoef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coeficients of polynom.
        /// </summary>
        internal static string PPolynomCoefDescription {
            get {
                return ResourceManager.GetString("PPolynomCoefDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to precision.
        /// </summary>
        internal static string PPrecision {
            get {
                return ResourceManager.GetString("PPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision of the calculation.
        /// </summary>
        internal static string PPrecisionDescription {
            get {
                return ResourceManager.GetString("PPrecisionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method of Runge-Kutta calculation (Normal | Adapted | Energy).
        /// </summary>
        internal static string PRungeKuttaDescription {
            get {
                return ResourceManager.GetString("PRungeKuttaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rungekutta.
        /// </summary>
        internal static string PRungeKuttaMethod {
            get {
                return ResourceManager.GetString("PRungeKuttaMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sr.
        /// </summary>
        internal static string PSamplingRate {
            get {
                return ResourceManager.GetString("PSamplingRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling rate of the signal.
        /// </summary>
        internal static string PSamplingRateDescription {
            get {
                return ResourceManager.GetString("PSamplingRateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string PSCoef {
            get {
                return ResourceManager.GetString("PSCoef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter s.
        /// </summary>
        internal static string PSCoefDescription {
            get {
                return ResourceManager.GetString("PSCoefDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signal.
        /// </summary>
        internal static string PSignal {
            get {
                return ResourceManager.GetString("PSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampled signal .
        /// </summary>
        internal static string PSignalDescription {
            get {
                return ResourceManager.GetString("PSignalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sizex.
        /// </summary>
        internal static string PSizeX {
            get {
                return ResourceManager.GetString("PSizeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of points in the X direction.
        /// </summary>
        internal static string PSizeXDescription {
            get {
                return ResourceManager.GetString("PSizeXDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sizey.
        /// </summary>
        internal static string PSizeY {
            get {
                return ResourceManager.GetString("PSizeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of points in the Y direction.
        /// </summary>
        internal static string PSizeYDescription {
            get {
                return ResourceManager.GetString("PSizeYDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spacing.
        /// </summary>
        internal static string PSpacing {
            get {
                return ResourceManager.GetString("PSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance of the neigbour components.
        /// </summary>
        internal static string PSpacingDescription {
            get {
                return ResourceManager.GetString("PSpacingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sqrmatrix.
        /// </summary>
        internal static string PSquareMatrix {
            get {
                return ResourceManager.GetString("PSquareMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square matrix.
        /// </summary>
        internal static string PSquareMatrixDescription {
            get {
                return ResourceManager.GetString("PSquareMatrixDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to startx.
        /// </summary>
        internal static string PStartingPoint {
            get {
                return ResourceManager.GetString("PStartingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting point of the interval.
        /// </summary>
        internal static string PStartingPointDetail {
            get {
                return ResourceManager.GetString("PStartingPointDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smatrix.
        /// </summary>
        internal static string PSymmetricMatrix {
            get {
                return ResourceManager.GetString("PSymmetricMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetrix matrix (in other hand the matrix will be symmetrized).
        /// </summary>
        internal static string PSymmetricMatrixDescription {
            get {
                return ResourceManager.GetString("PSymmetricMatrixDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        internal static string PTime {
            get {
                return ResourceManager.GetString("PTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of the evaluation.
        /// </summary>
        internal static string PTimeDescription {
            get {
                return ResourceManager.GetString("PTimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timestep.
        /// </summary>
        internal static string PTimeStep {
            get {
                return ResourceManager.GetString("PTimeStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time step for the result.
        /// </summary>
        internal static string PTimeStepDescription {
            get {
                return ResourceManager.GetString("PTimeStepDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uri.
        /// </summary>
        internal static string PURI {
            get {
                return ResourceManager.GetString("PURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI (link).
        /// </summary>
        internal static string PURIDescription {
            get {
                return ResourceManager.GetString("PURIDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x.
        /// </summary>
        internal static string PValue {
            get {
                return ResourceManager.GetString("PValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string PValueDescription {
            get {
                return ResourceManager.GetString("PValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var.
        /// </summary>
        internal static string PVariable {
            get {
                return ResourceManager.GetString("PVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable.
        /// </summary>
        internal static string PVariableDescription {
            get {
                return ResourceManager.GetString("PVariableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to varname.
        /// </summary>
        internal static string PVarName {
            get {
                return ResourceManager.GetString("PVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the variable.
        /// </summary>
        internal static string PVarNameDescription {
            get {
                return ResourceManager.GetString("PVarNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v.
        /// </summary>
        internal static string PVector {
            get {
                return ResourceManager.GetString("PVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vector.
        /// </summary>
        internal static string PVectorDescription {
            get {
                return ResourceManager.GetString("PVectorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x.
        /// </summary>
        internal static string PX {
            get {
                return ResourceManager.GetString("PX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable x.
        /// </summary>
        internal static string PXDetail {
            get {
                return ResourceManager.GetString("PXDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polynomial regression of data.
        /// </summary>
        internal static string RegressionHelp {
            get {
                return ResourceManager.GetString("RegressionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pv.
        /// </summary>
        internal static string RegressionP1 {
            get {
                return ResourceManager.GetString("RegressionP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input data for the regression.
        /// </summary>
        internal static string RegressionP1Description {
            get {
                return ResourceManager.GetString("RegressionP1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes bad points (NaN, Infinity) from Vector or PointVector.
        /// </summary>
        internal static string RemoveBadPointsHelp {
            get {
                return ResourceManager.GetString("RemoveBadPointsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of the radial part of basis wave function for 5D LHO.
        /// </summary>
        internal static string RWF5DLHOHelp {
            get {
                return ResourceManager.GetString("RWF5DLHOHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the value of the variable from the context; If there the variable does not exist, returns default value..
        /// </summary>
        internal static string SafeValueHelp {
            get {
                return ResourceManager.GetString("SafeValueHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates matrix with Poincaré section by the plane y = 0 for 2D system; contours are determined by SALI.
        /// </summary>
        internal static string SALIGHelp {
            get {
                return ResourceManager.GetString("SALIGHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculates SALI dependence on time for given trajectory.
        /// </summary>
        internal static string SALIHelp {
            get {
                return ResourceManager.GetString("SALIHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distinguishes using SALI whether the trajectory is regular (1) or chaotic (0).
        /// </summary>
        internal static string SALIRHelp {
            get {
                return ResourceManager.GetString("SALIRHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets a new context.
        /// </summary>
        internal static string SetContextHelp {
            get {
                return ResourceManager.GetString("SetContextHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given value or Vector of values put onto diagonal of square matrix.
        /// </summary>
        internal static string SetDiagonalHelp {
            get {
                return ResourceManager.GetString("SetDiagonalHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets a new global context.
        /// </summary>
        internal static string SetGlobalContextHelp {
            get {
                return ResourceManager.GetString("SetGlobalContextHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets a variable into the global context.
        /// </summary>
        internal static string SetGlobalVarHelp {
            get {
                return ResourceManager.GetString("SetGlobalVarHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given value put onto nondiagonal elements of square matrix.
        /// </summary>
        internal static string SetNonDiagonalHelp {
            get {
                return ResourceManager.GetString("SetNonDiagonalHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a graph.
        /// </summary>
        internal static string ShowHelp {
            get {
                return ResourceManager.GetString("ShowHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinus of the value.
        /// </summary>
        internal static string SinHelp {
            get {
                return ResourceManager.GetString("SinHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you do want to compute an effective interaction for coupled-cluster calculations you need to specify three files, one for the interaction itself, one for the kinetic energies of all sp orbits and one for sp data declarations. These files are in turn used as input to coupled-cluster calculations..
        /// </summary>
        internal static string SMCC_file {
            get {
                return ResourceManager.GetString("SMCC_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you specify if you wish to exclude CIB..
        /// </summary>
        internal static string SMCib_choice {
            get {
                return ResourceManager.GetString("SMCib_choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determine if you wish to include the Coulomb interaction or not..
        /// </summary>
        internal static string SMCoulomb_included {
            get {
                return ResourceManager.GetString("SMCoulomb_included", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you specify if you wish to exclude CSB..
        /// </summary>
        internal static string SMCsb_choice {
            get {
                return ResourceManager.GetString("SMCsb_choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The oscillator energy in MeV (We can change a look, if there is some change).
        /// </summary>
        internal static string SMHbar_omega {
            get {
                return ResourceManager.GetString("SMHbar_omega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determine whether you want to do Hartree-Fock or not. Options are 1) hf_iterations = 0 or 2) hf_iterations = 1 or any number larger than 0..
        /// </summary>
        internal static string SMHf_iterations {
            get {
                return ResourceManager.GetString("SMHf_iterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you do Hartree-Fock, the new interaction is given by this file..
        /// </summary>
        internal static string SMHFrenorminteraction_file {
            get {
                return ResourceManager.GetString("SMHFrenorminteraction_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new single-particle in case you do a Hartree-Fock calculation..
        /// </summary>
        internal static string SMHFspdata_file {
            get {
                return ResourceManager.GetString("SMHFspdata_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the NN interaction you need to define the min and max value of J for the partial waves. Typical values are 0 and 6. For the argonne interactions Jmax &lt;= 4. For waves greater than J_max, the Hamiltonian is set to zero in this version of the program..
        /// </summary>
        internal static string SMJminmax {
            get {
                return ResourceManager.GetString("SMJminmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define the maximum values of l for the model space. For square the model space 2n+l is entirely defined by lab_lmax..
        /// </summary>
        internal static string SMLab_lmax {
            get {
                return ResourceManager.GetString("SMLab_lmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define the maximum values of n for the model space. For square the model space 2n+l is entirely defined by lab_lmax..
        /// </summary>
        internal static string SMLab_nmax {
            get {
                return ResourceManager.GetString("SMLab_nmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give the number of nucleons, recall that for nocore the results depend on A..
        /// </summary>
        internal static string SMMass_nucleus {
            get {
                return ResourceManager.GetString("SMMass_nucleus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you do nocore, you need also to specify the cut in 2n+l for the huge space, use 200-300 for interactions like cdbonn or argonne  use 300..
        /// </summary>
        internal static string SMMax_space {
            get {
                return ResourceManager.GetString("SMMax_space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also compute results to a given order in many-body perturbation theory, in this case to third order. For coupled-cluster you have to stay with first order..
        /// </summary>
        internal static string SMOrder_of_interaction {
            get {
                return ResourceManager.GetString("SMOrder_of_interaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to output_run is prefixed to output file for optional printouts, tests etc..
        /// </summary>
        internal static string SMOutput_run {
            get {
                return ResourceManager.GetString("SMOutput_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the type of model space, three choices: square, triangular or wings. For the nocore calculation you can only use the triangular choice.
        /// </summary>
        internal static string SMPauli_operator {
            get {
                return ResourceManager.GetString("SMPauli_operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file for the renormalized NN interaction..
        /// </summary>
        internal static string SMRenorminteraction_fileI {
            get {
                return ResourceManager.GetString("SMRenorminteraction_fileI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file for the renormalized NN interaction..
        /// </summary>
        internal static string SMRenorminteraction_fileO {
            get {
                return ResourceManager.GetString("SMRenorminteraction_fileO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file for the set of single-particle orbits, this file can be further manipulated by the effective interaction part..
        /// </summary>
        internal static string SMSpdata_fileI {
            get {
                return ResourceManager.GetString("SMSpdata_fileI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file for the set of single-particle orbits, this file can be further manipulated by the effective interaction part..
        /// </summary>
        internal static string SMSpdata_fileO {
            get {
                return ResourceManager.GetString("SMSpdata_fileO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you do the g-matrix you need to specify the number of starting energies and their corresponding values. Typically you would use some 5 or more starting energies and they should all be smaller than the binding energy of the deuteron in order to avoid poles in the computation of G(w). The present code does not allow you to use positive starting energies. Typical start and end values are listed here. Based on the endpoints of the interval, the next values are generated by the simple algo first_value + inter [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SMStartenergy_g {
            get {
                return ResourceManager.GetString("SMStartenergy_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can compute the various diagrams for a given starting energy and then sum folded diagrams to infinite order. Typical starting energies for calculation should correspond to roughly the two-body energy of the valence nucleons. It should be negative since you are dealing with bound systems. If you choose just one  starting energy, then no folded diagrams are summed up..
        /// </summary>
        internal static string SMStartingEnergy {
            get {
                return ResourceManager.GetString("SMStartingEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determine what kind of effective interaction you want and the type of calculation. If you type shell-model, the code will produce an effective interaction taylored to the Oslo shell-model code, separated in three files, one for the pp case, one for pn and one for nn. For coupled-cluster calculations you will produce a file containing the effective interaction, one containing the kinetic energy and one for the total single-particle energies. You can also compute the binding energy of various closed core nucl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SMType_of_interaction {
            get {
                return ResourceManager.GetString("SMType_of_interaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the type of NN interaction, here you can use Idaho-A, Idaho-B, CD-bonn, argonnev18, n3lo, argonnev8. There is an important point concerning the different interaction models. Idaho-A and Idaho-B have NO charge-symmetry (CSB) or charge-independence breaking terms (ISB). The Argonne potentials run only with full CSB and CIB. The N3LO and CD-bonn models allow you to run with or without one or both of these terms. NO CSB means that for a given set of qauntum numbers ( a specific partial wave) the neutron [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SMType_of_pot {
            get {
                return ResourceManager.GetString("SMType_of_pot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determine the renormalization procedure you want to do, only one at the time..
        /// </summary>
        internal static string SMType_of_renormv {
            get {
                return ResourceManager.GetString("SMType_of_renormv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you wan to compute an effective interaction for the Oslo shell-model codes, you need to define the names of three files, one for the proton-proton case one for the proton-neutron case and finally one for the neutron-neutron case..
        /// </summary>
        internal static string SMVeff_xx {
            get {
                return ResourceManager.GetString("SMVeff_xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you do Vlowk you need to specify the number of mesh points for the model space and the large space. You need also to define the cutoff for the model in space in fm^- 1 and the in principal infinite integration limit set it to 20 fm^-1.  Recall that the NN interactions is fitted up to 350 MeV..
        /// </summary>
        internal static string SMVlowk {
            get {
                return ResourceManager.GetString("SMVlowk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending sort of the object (with keys according to the sorting will be done).
        /// </summary>
        internal static string SortDescHelp {
            get {
                return ResourceManager.GetString("SortDescHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending sort of the object (with keys according to the sorting will be done).
        /// </summary>
        internal static string SortHelp {
            get {
                return ResourceManager.GetString("SortHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object to sort (Sortable) [; Keys (Sortable)].
        /// </summary>
        internal static string SortParams {
            get {
                return ResourceManager.GetString("SortParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculates neighbour spacing of vector components v_{i+j} - v_{i}.
        /// </summary>
        internal static string SpacingHelp {
            get {
                return ResourceManager.GetString("SpacingHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square root of the value.
        /// </summary>
        internal static string SqrtHelp {
            get {
                return ResourceManager.GetString("SqrtHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of absolute values of all elements in the object.
        /// </summary>
        internal static string SumAbsHelp {
            get {
                return ResourceManager.GetString("SumAbsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of all elements in the object.
        /// </summary>
        internal static string SumHelp {
            get {
                return ResourceManager.GetString("SumHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to int | double | TArray | Vector | Matrix.
        /// </summary>
        internal static string SumParameters {
            get {
                return ResourceManager.GetString("SumParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of squares of values of all elements in the object.
        /// </summary>
        internal static string SumSquareHelp {
            get {
                return ResourceManager.GetString("SumSquareHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tries to read text from specified URI.
        /// </summary>
        internal static string TestWWWHelp {
            get {
                return ResourceManager.GetString("TestWWWHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the duration of the calculation.
        /// </summary>
        internal static string TimeHelp {
            get {
                return ResourceManager.GetString("TimeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the current time.
        /// </summary>
        internal static string TimeNowHelp {
            get {
                return ResourceManager.GetString("TimeNowHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression.
        /// </summary>
        internal static string TimeParameters {
            get {
                return ResourceManager.GetString("TimeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given file must be text file, not binary..
        /// </summary>
        internal static string ToArrayEMNotTextFile {
            get {
                return ResourceManager.GetString("ToArrayEMNotTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given non-array object change to an array..
        /// </summary>
        internal static string ToArrayHelp {
            get {
                return ResourceManager.GetString("ToArrayHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string ToArrayParameters {
            get {
                return ResourceManager.GetString("ToArrayParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For given energy or a trajectory given by its initial condition calculates the trajectory; the result is returned by a matrix in the form (time, x, y, ..., px, py, ...).
        /// </summary>
        internal static string TrajectoryMHelp {
            get {
                return ResourceManager.GetString("TrajectoryMHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     For given energy or a trajectory given by its initial condition calculates the trajectory; the x, y coordinates of the result is returned by a PointVector.
        /// </summary>
        internal static string TrajectoryPHelp {
            get {
                return ResourceManager.GetString("TrajectoryPHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of the value.
        /// </summary>
        internal static string TypeHelp {
            get {
                return ResourceManager.GetString("TypeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses the given context for specified calculations.
        /// </summary>
        internal static string UseContextHelp {
            get {
                return ResourceManager.GetString("UseContextHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert given data to a vector.
        /// </summary>
        internal static string VectorHelp {
            get {
                return ResourceManager.GetString("VectorHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items of vector (int | double | Vector | Matrix | Array | List).
        /// </summary>
        internal static string VectorParameters {
            get {
                return ResourceManager.GetString("VectorParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of Wigner distribution.
        /// </summary>
        internal static string WignerHelp {
            get {
                return ResourceManager.GetString("WignerHelp", resourceCulture);
            }
        }
    }
}
