//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PavelStransky.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PavelStransky.Forms.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad file name: &apos;{0}&apos;.
        /// </summary>
        internal static string EMBadFileName {
            get {
                return ResourceManager.GetString("EMBadFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation error.
        /// </summary>
        internal static string EMCalculationError {
            get {
                return ResourceManager.GetString("EMCalculationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save data of all graph items as (animated) GIF.
        /// </summary>
        internal static string TSaveAllAnim {
            get {
                return ResourceManager.GetString("TSaveAllAnim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save data of all graph items as sequence of pictures.
        /// </summary>
        internal static string TSaveAllSeq {
            get {
                return ResourceManager.GetString("TSaveAllSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save data of all graph items as text.
        /// </summary>
        internal static string TSaveAllText {
            get {
                return ResourceManager.GetString("TSaveAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save data with size of the window and limits (for web).
        /// </summary>
        internal static string TSaveForWeb {
            get {
                return ResourceManager.GetString("TSaveForWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save data of one graph item as (animated) GIF.
        /// </summary>
        internal static string TSaveOneAnim {
            get {
                return ResourceManager.GetString("TSaveOneAnim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save data of one graph item as sequence of pictures.
        /// </summary>
        internal static string TSaveOneSeq {
            get {
                return ResourceManager.GetString("TSaveOneSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save data of one graph item as text.
        /// </summary>
        internal static string TSaveOneText {
            get {
                return ResourceManager.GetString("TSaveOneText", resourceCulture);
            }
        }
    }
}
